//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_FrameWorkk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int idEmployee { get; set; }
        public string nameEmpployee { get; set; }
        public Nullable<System.DateTime> birthEmployye { get; set; }
        public double workingEmployye { get; set; }
        public string statusEmployye { get; set; }
    }
}
